<?php

declare(strict_types=1);


namespace Frago9876543210\PocketEditionClient\protocol;


use Frago9876543210\PocketEditionClient\Address;
use pocketmine\network\mcpe\handler\SessionHandler;
use pocketmine\network\mcpe\NetworkBinaryStream;
use pocketmine\utils\UUID;

class LoginPacket extends DataPacket{
	public const NETWORK_ID = ProtocolInfo::LOGIN_PACKET;

	/** @var string */
	public $username;
	/** @var Address */
	public $serverAddress;

	protected function encodePayload() : void{
		$inputrand = array("SAMSUNG SM-T355", "XIAOMI Redmi 4X", "HUAWEI LLD-L31", "XIAOMI Redmi 6A", "HUAWEI DLI-TL20", "LENOVO Lenovo TB3-850M", "HUAWEI CRO-U00", "LGE LG-K580", "XIAOMI Redmi Note 7", "SONY F3311", "XIAOMI Redmi Note 4", "TCL 5059D_RU", "XIAOMI Redmi 5A");
		$input = array_rand($inputrand);
		$input228 = $inputrand[$input];
		$this->putInt(113);
		$this->putByte(0);
		$stream = new NetworkBinaryStream();
		$header = [
			"alg" => "ES384",
			"x5u" => $key = self::randomBytes(160)
		];
		$chain = json_encode([
			"chain" => [
				self::encodeJWT(
					$header,
					[
						"exp" => time() + 3600,
						"extraData" => [
							"displayName" => $this->username,
							"identity" => UUID::fromRandom()->toString()
						],
						"identityPublicKey" => $key,
						"nbf" => time() - 3600
					]
				)
			]
		]);
		$stream->putLInt(strlen($chain));
		$stream->put($chain);
		$sas = base64_decode("AAAA/wAAAP8CAgL/AAAA/wMDA/8GBgb/AAAA/wQEBP+EbBz/hW0c/5aWAP+FbRz/hGwc/4ZuHP+OdB7/hW0c//rIlv/6yJb/+siW//rIlv/6yJb/+siW//rIlv/6yJb/AAAA/wICAv8AAAD/AgIC/wUFBf8AAAD/BgYG/wYGBv8HBwf/AQEB/wYGBv8AAAD/BAQE/wEBAf8AAAD/AgIC/01OTf9QUVD/TU5N/09QT/9HSEf/R0hH/0lKSf9NTk3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGBgb/AAAA/wAAAP8AAAD/AAAA/wAAAP8DAwP/AAAA/wICAv8AAAD/AQEB/wAAAP8AAAD/AAAA/wAAAP8AAAD/iXAd/4pxHf9oaAD/kHYe/4pxHf+YmAD/jHMe/4tyHf/6yJb/+siW//rIlv/6yJb/+siW//rIlv/6yJb/+siW/wQEBP8AAAD/AAAA/wAAAP8AAAD/AAAA/wUFBf8AAAD/AwMD/wAAAP8GBgb/AQEB/wYGBv8AAAD/BAQE/wEBAf9HSEf/TU5N/1BRUP9YVlb/UFFQ/2JZWf9QUVD/SEhI/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMD/wAAAP8GBgb/AAAA/wAAAP8AAAD/AQEB/wMDA/8DAwP/AQEB/wAAAP8FBQX/AQEB/wAAAP8FBQX/AAAA/4hvHf+Lch3/jXMe/4hwHf+Lch3/hGwc/4pxHf+PdR7/+siW//rIlv/6yJb/+siW//rIlv/6yJb/+siW//rIlv8CAgL/AAAA/wMDA/8AAAD/AwMD/wEBAf8AAAD/BgYG/wAAAP8AAAD/AAAA/wAAAP8FBQX/AAAA/wUFBf8DAwP/Tk9O/1FSUf9bU1P/S0xL/0dHR/9LSkr/RkdG/0tMS/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8EBAT/AAAA/wAAAP8AAAD/AAAA/wAAAP8FBQX/AAAA/wAAAP8BAQH/AAAA/wUFBf8AAAD/AAAA/wYGBv+Rdh7/aGgA/4xyHf+FbRz/a2sA/4VtHP+Qdh7/hW0c//rIlv/6yJb/+siW//rIlv/6yJb/+siW//rIlv/6yJb/AgIC/wAAAP8CAgL/AgIC/wAAAP8BAQH/AAAA/wAAAP8AAAD/AwMD/wYGBv8EBAT/BgYG/wAAAP8AAAD/AAAA/1JTUv9JSEj/X11d/1JTUv9HSEf/SktK/1BRUP9XVVX/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGBgb/AAAA/wAAAP8AAAD/AQEB/wICAv8DAwP/AAAA/wQEBP8CAgL/BgYG/wAAAP8DAwP/AgIC/wYGBv8AAAD/hm4c/4hvHf+Gbhz/hm0c/410Hv+UlAD/jXQe/4VtHP/6yJb/+siW//rIlv/6yJb/+siW//rIlv/6yJb/+siW/wAAAP8GBgb/AAAA/wMDA/8BAQH/AQEB/wAAAP8GBgb/AwMD/wQEBP8AAAD/AAAA/wMDA/8AAAD/AAAA/wAAAP9GR0b/UVJR/19WVv9QUVD/TE1M/0xNTP9RUlH/SktK/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wEBAf8AAAD/AAAA/wMDA/8AAAD/BAQE/wAAAP8CAgL/AQEB/wICAv8AAAD/AAAA/wQEBP8BAQH/AAAA/41zHv+JcB3/np4A/4hvHf+PdR7/jXMe/2xsAP+Lch3/+siW//rIlv/6yJb/+siW//rIlv/6yJb/+siW//rIlv8AAAD/AAAA/wAAAP8AAAD/AQEB/wAAAP8BAQH/AgIC/wAAAP8AAAD/BAQE/wEBAf8BAQH/AAAA/wAAAP8FBQX/SElI/1FSUf9HSEf/SktK/1dPT/9RUlH/S0xL/0pLSv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBP8GBgb/AAAA/wQEBP8AAAD/AgIC/wAAAP8AAAD/AAAA/wYGBv8AAAD/AAAA/wAAAP8EBAT/AAAA/wAAAP+PdR7/hm4c/4RsHP9jYwD/iHAd/4VtHP+LcR3/h24c/wAAAP8AAAD/AAAA/2VlZf9lZWX/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8HBwf/AAAA/wQEBP8AAAD/AAAA/wICAv8EBAT/AAAA/wAAAP8AAAD/BAQE/01OTf9ISUj/UFFQ/0RDQ/9OT07/YmBg/0pLSv9SU1L/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wYGBv8DAwP/AAAA/wAAAP8AAAD/AwMD/wAAAP8AAAD/AAAA/wUFBf8EBAT/inEd/410Hv+Gbhz/inEd/410Hv+PdR7/i3Id/4pxHf/6yJb/+siW//rIlv/6yJb/+siW//rIlv/6yJb/+siW/wICAv8AAAD/AAAA/wAAAP8AAAD/AAAA/wUFBf8GBgb/AAAA/wYGBv8AAAD/AwMD/wAAAP8EBAT/AAAA/wICAv9NTk3/SktK/1NUU/9GR0b/RkdG/0tMS/9MTUz/TU5N/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQUF/wAAAP8FBQX/AAAA/wMDA/8CAgL/AQEB/wQEBP+niB//p4gf/6eIH/+niB//p4gf/6eIH/+niB//p4gf/5+CHv/NzQD/lpYA/6iJH/+mhx//pIYf/6CCHv+niB//oIIe/6yLIP+sjCD/zc0A/6iJH/+khR//pIUf/6CCHv+khR//rIwg/5mZAP+piSD/pocf/6SGH/+lhx//q4sg/01OTf9HSEf/UVJR/05PTv9JSkn/Tk9O/01OTf9NTk3/TU5N/05PTv9OT07/TEtL/1dVVf9KS0r/UlNS/01OTf9NTk3/UlNS/0dIR/8RERH/ERER//39/f9GRkb/TU5N/01OTf9SU1L/UlNS/0ZHRv9GR0b/S0xL/0hISP9NTk3/p4gf/6eIH/+niB//p4gf/6eIH/+niB//p4gf/6eIH/+YmAD/p4gf/6CCHv+ggh7/qosg/6yMIP+goAD/pIUf/6uLIP+oiR//q4sg/6iJH/+amgD/oYMe/6GDHv+piSD/qoog/6WGH/+ggh7/q4sg/6iIH/+mhx//0dEA/6CCHv9IR0f/SElI/0dIR//S0tL/R0hH/83Nzf9LTEv/R0ZG/1hQUP9SU1L/VlRU/0RDQ/9SU1L/RURE/09QT/9aUlL/TU5N/11VVf9FRET/ERER///////OAAD/TEtL/1FTUf9ISUj/WlhY/0ZHRv9LTEv/TUxM/1JTUv9iWVn/Xlxc/6eIH/+niB//p4gf/6eIH/+niB//p4gf/yQkJP+mhx//qoog/6yMIP//zJn//8yZ//zKl///zJn/pocf/6WGH/+mhx//Hh4e/6WGH/+riyD/oYMe/6SGH/+hgx7/qIgf/6WGH/+ggh7/z88A/6OEHv+qiiD/oYMe/6qKIP+hgx7/TU5N/01OTf/MzMz/TlBO/9HR0f9KS0r/TU5N/0lKSf8WFhb/FhYW/xYWFv8WFhb/FhYW/xYWFv8WFhb/FhYW/1tZWf9NTk3/UFFQ///////KAAD/1QAA/01OTf9QUVD/T1BP/0ZHRv9KS0r/Tk9O/0ZHRv9HSEf/RkdG/1JTUv+niB//p4gf/6eIH/+niB//p4gf/6GDHv8UFBT/+MeV//zJl/8AAAD/AAAA///Mmf/6yJb/AAAA/wAAAP/5x5X//cqY/xEREf+piSD/q4sg/6eIH/+niB//p4gf/6eIH/+niB//qIgf/6WGH/+ggh7/pocf/6yMIP+riyD/p4gf/1FSUf9RUlH/UlNS/1BRUP8WFhb/FhYW/xYWFv8WFhb/FhYW/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYWFv8aGhr/Ghoa/xYWFv8WFhb/T1BP/09QT/9LTEv/S0xL/1FSUf9eVlb/UlNS/11VVf9PUE//RkZG/0dIR/9ISUj/p4gf/6eIH//+zJn/+siW/6CCHv+niB//AAAA//jGlf//zJn/+fn5/83ZKf/7yZf//8yZ/83ZKf/9/f3/+MeV//zJl/8AAAD/qIgf/6qKIP//zJn//8yZ/6eIH/+niB//p4gf/6eIH/+nhx//o4Qe/5SUAP+lhh//p4gf/6eIH/9SU1L/WFZW/xYWFv8WFhb/FhYW/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhYW/xYWFv8WFhb/RkdG/0tMS/9GR0b/SUpJ/0dIR/9PUE//S0tL/2JaWv9GR0b/UlNS//rIlv/9ypj//suY///LmP/8ypf//8yZ/wAAAP/0w5L/+siW//7Mmf/7yZf/+ceV//nHlf//zJn/98aV///Mmf//zJn/AwMD///Mmf//zJn/9MOS//vJl//4x5X//cqY///Mmf+niB//p4gf/6iJH/+khh//pocf/6eIH//8ypf/FhYW/xYWFv8WFhb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhYW/xYWFv8WFhb/FhYW/xYWFv9SU1L/SElI/09QT/9PUE//FhYW/xYWFv//zJr//cqY///Mmf//zJn//8yZ///Mmv8AAAD//8yZ//7Mmf//zJn////////////////////////Mmf//zZn/98aU/wYGBv//zJn//MqX///Mmf/5x5X//MuY//rIlv/8yZf/+ciW/6eIH/+mhx//qYkf/6eIH///zJj/+MeV/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFhb/FhYW/xYWFv8WFhb/FhYW/xYWFv8AAAAA/8yZ//nHlv/3xZT//cqY//bFlP//zJn/BQUF//TDk//7yZf//8yZ///Mmf/7yZf/98WU///Mmf//zJn//syZ//zKl/8EBAT//8yZ//rIlv//zJn/+MeV///Mmf/9ypj//8yZ///Mmf/7yJb//8yZ//vJlv//zJn/+ceV//zJl/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAD/gIACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDA/8AAAD/AAAA/wAAAP8cHx7/GRwb/xgbGv8WGBf/CQoH/wkKB/8JCgf/BgYG/05PTv9RUlH/UFFQ/0xNTP9MTUz/SUpJ/09QT/9RUlH/Kich/1Q1Bf9UNQX/VDUF/1Q1Bf9UNQX/TTII/x0dHf8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/0lKSf9OT07/T1BP/09QT/9SVFL/TU5N/05QTv9PUE//ISQj/ygnJv8zHBv/OzYs/wAAAP8AAAD/AAAA/wUFBf8DAwP/AAAA/wAAAP8EBAT/AAAA/wAAAP8AAAD/BgYG/wUFBf8AAAD/AQEB/wAAAP8AAAD/AAAA/wICAv8AAAD/ISQj/yEkI/8gIyL/GRsa/wkKB/8JCgf/CQoH/wYGBv9HSEf/Tk1N/1dQUP9OT07/TU5N/1dWVv9eVlb/TU5N/yMgGv9UNQX/+siW//rIlv/6yJb/+siW/00yCP8dHR3/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/9KS0r/RkdG/2JgYP9OT07/R0ZG/0hJSP9NTk3/SklJ/ygnJv9sOzv/qQwM/zw2Lv8EBAT/AAAA/wEBAf8AAAD/AAAA/wAAAP8AAAD/AwMD/wICAv8CAgL/AAAA/wMDA/8AAAD/AAAA/wAAAP8AAAD/AAAA/wUFBf8AAAD/AgIC/yAjIv8gIyL/HyIh/xwfHf8JCgf/CQoH/wkKB/8GBgb/R0hH/2BXV/9fXV3/TU5N/0hJSP9NTk3/SktK/09QT/8jIBr/VDUF//rIlv/6yJb/+siW//rIlv9NMgj/HR0d/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/T1BP/09QT/9fV1f/RkdG/0xLS/9KS0r/R0hH/0lKSf84IB//yAwM/0FCQv88Ni7/AAAA/wAAAP8AAAD/AAAA/wMDA/8AAAD/AAAA/wUFBf8AAAD/BQUF/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wEBAf8AAAD/AAAA/wICAv8fIiH/HB8e/xocG/8dHx7/CwwJ/wsMCf8LDAr/CAgI/09QT/9GR0b/WlJS/0dIR/9NTk3/T1BP/1FSUf9LTEv/Ih8a/00yB/9SNAT/Si4E/0svBP9TNAX/Ri8K/x0dHf8gIyL/ICMi/yAjIv8gIyL/ICMi/yAjIv8gIyL/ICMi/0pLSv9MTUz/SUpJ/0ZHRv9NTk3/Tk9O/0ZHRv9PUE//ISQj/yEkI/8hJCP/ODQs/wAAAP8BAQH/BQUF/wQEBP8AAAD/AAAA/wAAAP8AAAD/AAAA/wcHB/8AAAD/AQEB/wMDA/8CAgL/BQUF/wMDA/8eISD/HiEg/xkbGv8gIyL/HyIh/xgbGv8ZGxr/GRsa/xweHf8aHBv/HiEg/x4hIP8fIiH/Ghwc/xkbG/8bHRz/BAQE/wQEBP8DAwP/AwMD/xkZGf8jIBr/Si4E/wQEBP8OCgT/TjMJ/ycnKP8dHR3/HR0d/x0dHf8dHR3/HR0d/x0dHf8dHR3/HR0d/x0dHf8dHR3/HR0d/xwdHf8aGhr/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ICAg/wEBAf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/HiEg/xkcG/8gIyL/HiEg/x4hIP8fIiH/ICMi/xwfHv8dIB//HSAf/yAjIv8hJCP/ISQj/yAjIv8aHRz/HB8e/yEkI/8hJCP/HSAf/wMDA/8DAwP/HxwX/0QsB/8GBgb/DgsF/1E6Ff9paWr/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yAjIv8YGxr/BgYG/zU4N/82OTj/NjU0/zY1NP82NTT/NjU0/zY1NP82NTT/NjU0/zY1NP82NTT/NjU0/zY1NP82NTT/NjU0/zU6Nf8DAwP/AQEB/wQEBP8AAAD/AgIC/wAAAP8FBQX/AwMD/x8iIf8gIyL/HyEg/yAjIv8dIB//ICMi/yAjIv8fIiH/HB8e/yAjIv8eISD/ICMi/yAjIv8eISD/Gx4d/x4hIP8hJCP/ISQj/yEkI/8dIB//AwMD/wMDA/8ZGRn/Gxsb/xMUFP8iIiL/IyMj/yUoJ/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yAjIv8YGxr/AAAA/wECAf8hJCP/ISQj/zY1NP8hJCP/ISQj/zY1NP8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/NjU0/yEkI/8hJCP/AAAA/wAAAP8AAAD/AwMD/wAAAP8AAAD/BwcH/wQEBP8gIyL/HyIh/xkbGv8fIiH/GRwb/yAjIv8aHBv/Gx4d/x4hIP8eISD/Gx4d/xwfHv8fIiH/FxkY/xocG/8dHx7/ISQj/yEkI/8hJCP/ISQj/x0gH/8DAwP/AwMD/2JiYv8cHRz/UFBQ/0VFRf9BQkL/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yAjIv8YGxr/AAAA/wECAf8cHx7/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/wAAAP8BAQH/AAAA/wAAAP8AAAD/AwMD/wAAAP8AAAD/HSAf/x4hIP8bHh3/HyIh/xkbGv8fIiH/FxkZ/xodHP8eISD/HSAf/x8hIf8hJCP/ICMi/x0gH/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/HSAf/wMDA/8CAgL/Hh8e/yEkI/9oaGn/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yAjIv8YGxr/AAAA/wECAf8hJCP/HyIh/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8CAgL/BQUF/wAAAP8AAAD/AAAA/wEBAf8BAQH/BQUF/x4gH/8XGRj/HB8e/x4hIP8ZHBv/HyEg/xweHf8cHh3/HR8f/xcaGf8eISD/HyIh/x8iIf8fIiH/HyIh/x8iIf8hJCP/ISQj/yEkI/8hJCP/ISQj/yIlJP8nKin/YmJi/wMDA/8bHh3/FxkY/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yAjIv8YGxr/AQIB/wcIB/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/AAAA/wICAv8FBQX/BgYG/wICAv8AAAD/AAAA/wAAAP8SExL/EhMS/xITEv8SExL/EhMS/wECAf8BAgH/EhMS/xITEv8SExL/EhMS/xITEv8SExL/EhMS/xITEv8UFRT/ISQj/yEkI/8hJCP/ISQj/yEkI/8rLi3/ICEg/xwfHv8BAQH/AwMD/x0gH/8hJCP/ISQj/yEkI/8hJCP/ISQj/yAjIv8YGxr/AAAA/wECAf8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/wMDA/8AAAD/AAAA/wICAv8AAAD/BgYG/wAAAP8EBAT/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/BAQE/yEkI/8hJCP/ISQj/yEkI/8hJCP/IiUk/ysuLf9iYmL/ERIR/wECAf8DAwP/HSAf/yEkI/8hJCP/ISQj/yAjIv8YGxr/AAAA/wECAf8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8mKSj/JSgn/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8AAAD/AwMD/wAAAP8DAwP/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wMDA/8cHx7/HB8e/xwfHv8cHx7/HB8e/yYpKP8gISD/HSAf/yAhIP8iJST/AAAA/wMDA/8cHx7/HB8e/xwfHv8YGxr/AAAA/wECAf8cHx7/HB8e/xwfHv8cHx7/HB8e/x0gH/8hJCP/RkdG/0FCQv8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/AAAA/wUFBf8DAwP/AAAA/wMDA/8GBgb/AAAA/wAAAP8AAAD/AAAA/wEBAP8BAQD/AQEA/wEBAP8BAQD/AQEA/wEBAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wMDA/8GBgb/AAAA/4B/f/9+fX3/AAAA/wAAAP8CAgL/AAAA/wQEBP8BAQH/BQUF/wQEBP8AAAD/AAAA/wAAAP8EBAT/BQUF/wUFBf8ICAj/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/wMDA/8EBAT/AAAA/wUFBf8AAAD/AAAA/wAAAP8AAAD/CQoH/wECAf8BAgH/AQIB/wECAf8BAgH/AQIB/wECAf8JCgf/BwgG/wEBAP8BAQD/CQoH/wkKB/8JCgf/CQoH/wAAAP8AAAD/BgYG/wAAAP8AAAD/AAAA/wAAAP+BgID/g4KC/wAAAP8GBgb/AAAA/wEBAf8EBAT/BAQE/wcHB/8AAAD/AAAA/wUFBf8EBAT/AAAA/wMDA/8BAQH/BwcH/wAAAP8AAAD/AAAA/wAAAP8ICAj/AQEB/wAAAP8EBAT/AAAA/wAAAP8FBQX/AAAA/wAAAP8AAAD/AAAA/wAAAP8BAQH/AgIC/wQEBP8DAwP/AAAA/wAAAP8AAAD/AAAA/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/woLCP8VFhX/FRYV/xUWFf8VFhX/FRYV/xUWFf8VFhX/FRYV/xUWFf8VFhX/FRYV/xUWFf8VFhX/FRYV/xUWFf8VFhX/FRYV/xUWFf8VFhX/FRYV/xUWFf8VFhX/FRYV/xUWFf8AAAD/BgYG/wEBAf8BAQH/AAAA/wICAv8AAAD/BwcH/wMDA/8EBAT/AQEB/wMDA/8AAAD/AgIC/wAAAP8AAAD/AQEB/wAAAP8EBAT/AQEB/wAAAP8EBAT/BgYG/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkKB/8JCgf/CQoH/wYGBv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCgf/CQoH/wkKB/8GBgb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQoH/wkKB/8JCgf/BgYG/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkKB/8JCgf/CQoH/wYGBv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABELAf/AAAAAAAAAABROhX/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdHR3/HR0d/x0dHf8dHR3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAFBQUP9BQkL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAAAAAAAAaGhp/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8hIP8cHh3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAgH/AQIB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDgoL/g4KC/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg4KC/4OCgv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGBgb/CQoH/wkKB/8JCgf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWGBf/GBsa/xkcG/8cHx7/BgYG/wkKB/8JCgf/CQoH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOzYs/zMcG/8oJyb/ISQj/wUFBf8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgYG/wkKB/8JCgf/CQoH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRsa/yAjIv8hJCP/ISQj/wYGBv8JCgf/CQoH/wkKB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw2Lv+pDAz/bDs7/ygnJv8AAAD/AQEB/wAAAP8EBAT/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGBv8JCgf/CQoH/wkKB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwfHf8fIiH/ICMi/yAjIv8GBgb/CQoH/wkKB/8JCgf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8Ni7/QUJC/8gMDP84IB//AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGBgb/CQoH/wkKB/8JCgf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdHx7/Ghwb/xwfHv8fIiH/CAgI/wsMCv8LDAn/CwwJ/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODQs/yEkI/8hJCP/ISQj/wQEBP8FBQX/AQEB/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeISD/HiEg/xocG/8cHh3/GRsa/xkbGv8YGxr/HyIh/yAjIv8ZGxr/HiEg/x4hIP8bHRz/GRsb/xocHP8fIiH/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ICAg/yEkI/8hJCP/ISQj/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAISQj/yAjIv8dIB//HSAf/xwfHv8gIyL/HyIh/x4hIP8eISD/ICMi/xkcG/8eISD/HB8e/xodHP8gIyL/ISQj/zY1NP82NTT/NjU0/zY1NP82NTT/NjU0/zY1NP82NTT/NjU0/zY1NP82NTT/NjU0/zY1NP82NTT/NjU0/zY1NP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAjIv8eISD/ICMi/xwfHv8fIiH/ICMi/yAjIv8dIB//ICMi/x8hIP8gIyL/HyIh/x4hIP8bHh3/HiEg/yAjIv8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/82NTT/ISQj/yEkI/82NTT/ISQj/yEkI/8hJCP/ISQj/zY1NP8hJCP/rwQE/68EBP+vBAT/rwQE/8kAAP/JAAD/yQAA//Dw8P/w8PD/AAAA/wAAAP/w8PD/rwQE/68EBP/JAAD/rwQE/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcHx7/Gx4d/x4hIP8eISD/Gx4d/xocG/8gIyL/GRwb/x8iIf8ZGxr/HyIh/yAjIv8dHx7/Ghwb/xcZGP8fIiH/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/8kAAP/cAAD/zAAA/8kAAP/nAAD/zAAA//Dw8P8AAAD/8PDw/wAAAP/w8PD/8PDw//Dw8P+vBAT/yQAA/8kAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAISQj/x8hIf8dIB//HiEg/xodHP8XGRn/HyIh/xkbGv8fIiH/Gx4d/x4hIP8dIB//ISQj/yEkI/8dIB//ICMi/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI//JAAD/3AAA/+cAAP/nAAD/3AAA/+cAAP/w8PD/AAAA/wAAAP8AAAD/AAAA/wAAAP/w8PD/yQAA/8kAAP/JAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAcHh3/HyEg/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8iIf8eISD/FxoZ/x0fH/8cHh3/HB4d/x8hIP8ZHBv/HiEg/xwfHv8XGRj/HiAf/x8iIf8fIiH/HyIh/x8iIf8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/yQAA/+cAAP/MAAD/zAAA/8wAAP/cAAD/8PDw//Dw8P/w8PD/AAAA//Dw8P8AAAD/8PDw/8wAAP/JAAD/yQAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAQIB/wECAf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASExL/EhMS/xITEv8SExL/EhMS/wECAf8BAgH/EhMS/xITEv8SExL/EhMS/xITEv8UFRT/EhMS/xITEv8SExL/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/68EBP/JAAD/rwQE/8kAAP+vBAT/yQAA/68EBP/w8PD/AAAA/wAAAP/w8PD/8PDw/68EBP/JAAD/rwQE/68EBP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/BAQE/wAAAP8AAAD/AAAA/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yEkI/8hJCP/ISQj/yUoJ/8lKCf/ISQj/yEkI/8hJCP/ISQj/yEkI/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wMDA/8AAAD/AAAA/wAAAP9BQkL/QUJC/0FCQv9BQkL/QUJC/0FCQv9BQkL/QUJC/0FCQv9GR0b/QUJC/0FCQv9BQkL/QUJC/0FCQv9BQkL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8BAQD/AQEA/wEBAP8BAQD/AQEA/wEBAP8BAQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8aHBv/Ghwb/xocG/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEA/wEBAP8HCAb/CQoH/wECAf8BAgH/AQIB/wECAf8BAgH/AQIB/wECAf8JCgf/CQoH/wkKB/8JCgf/CQoH/wAAAP8FBQX/AAAA/wAAAP8EBAT/AAAA/wEBAf8ICAj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8AAAAAAAAAAAAAAAAAAAAACQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/wkKB/8JCgf/CQoH/woLCP8JCgf/CQoH/wkKB/8DAwP/AQEB/wQEBP8DAwP/BwcH/wAAAP8CAgL/AAAA/wEBAf8BAQH/BgYG/wAAAP8AAAD/AAAA/wICAv8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==");
		$client = self::encodeJWT(
			$header,
			[
				"ADRole" => 2,
				"ClientRandomId" => rand(),
				"CurrentInputMode" => 2,
				"DefaultInputMode" => 2,
				"DeviceModel" => "$input228",
				"DeviceOS" => 1,
				"GameVersion" => "1.1.5",
				"GuiScale" => 0,
				"LanguageCode" => "ru_RU",
				"ServerAddress" => $this->serverAddress->ip . ":" . $this->serverAddress->port,
				"SkinData" => base64_encode("$sas"),
				"SkinId" => "Standard_Custom",
				"TenantId" => "",
				"UIProfile" => 1
			]
		);
		$stream->putLInt(strlen($client));
		$stream->put($client);
		$this->putString($stream->buffer);
	}

	//JWT
	public static function encodeUrl(string $data){
		return rtrim(strtr(base64_encode($data), '+/', '-_'), '=');
	}

	public static function encodeJWT(array $header, array $payload){
		return self::encodeUrl(json_encode($header)) . "." . self::encodeUrl(json_encode($payload)) . "." . self::randomBytes(96);
	}

	public static function randomBytes(int $len) : string{
		/** @noinspection PhpUnhandledExceptionInspection */
		return substr(self::encodeUrl(random_bytes($len)), 0, $len);
	}

	public static function randomString($length){
		$characters = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
		$charactersLength = strlen($characters);
		$randomString = "";
		for($i = 0; $i < $length; $i++){
			$randomString .= $characters[rand(0, $charactersLength - 1)];
		}
		return $randomString;
	}

	public function handle(SessionHandler $handler) : bool{
		return false;
	}
	
		public function getA() : int{
		return $this->a;
	}

	public function setA(int $a){
		$this->a = 1.0 & 0xff;
	}

		public function getR() : int{
		return $this->r;
	}

	public function setR(int $r){
		$this->r = 255 & 0xff;
	}

	public function getG() : int{
		return $this->g;
	}

	public function setG(int $g){
		$this->g = 255 & 0xff;
	}

	public function getB() : int{
		return $this->b;
	}

	public function setB(int $b){
		$this->b = 0 & 0xff;
	}


	public static function fromRGB(int $code){
		return new Color(($code >> 16) & 0xff, ($code >> 8) & 0xff, $code & 0xff);
		$clr = $this->Color;
	}
}